apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "8001"
    port: 8001
    targetPort: 80
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
